---
title: "R Notebook"
output: html_notebook
---

### Alan Hurtarte
#### 19000590

---

# Boston dataset
### Head of Boston dataset

```{r echo=TRUE}
library(MASS)
library(ISLR)

head(Boston)
```

# Simple linear regression

---

```{r echo=TRUE}
lm.fit <- lm(medv~lstat, data = Boston)
attach(Boston)
lm.fit <- lm(medv~lstat)
summary(lm.fit)
```

```{r echo=TRUE}
names(lm.fit)
```
```{r echo=TRUE}
coef(lm.fit)
```
```{r echo=TRUE}
confint(lm.fit)
```
```{r echo=TRUE}
predict(lm.fit, data.frame(lstat = c(5, 10, 15)), interval = 'confidence')
```
```{r echo=TRUE}
predict(lm.fit, data.frame(lstat = c(5, 10, 15)), interval = 'prediction')
```
```{r echo=TRUE}
{
  plot(lstat, medv, pch = 20);
  abline(lm.fit, lwd = 3, col = 'red')
  }
```

```{r echo=TRUE}
{
  plot(predict(lm.fit), residuals(lm.fit), pch = 20);
  }
```
```{r echo=TRUE}
{
  plot(predict(lm.fit), rstudent(lm.fit), pch = 20);
  }
```
```{r echo = TRUE}
plot(hatvalues(lm.fit))
```

The which.max() function identifies the index of the largest element of a which.max() vector. In this case, it tells us which observation has the largest leverage
statistic.
```{r echo = TRUE}
which.max(hatvalues(lm.fit))
```

# Multiple Linear Regression

---

```{r echo=TRUE}
lm.fit <- lm(medv~lstat+age ,data=Boston )
summary (lm.fit)
```

```{r echo=TRUE}
lm.fit <- lm(medv~. ,data=Boston )
summary (lm.fit)
```
```{r echo=TRUE}
lm.fit <- lm(medv~.-age ,data=Boston )
summary (lm.fit)
```

```{r echo=TRUE}
summary (lm(medv~lstat*age ,data=Boston))
```

```{r echo=TRUE}
lm.fit2 <- lm(medv~lstat+I(lstat^2))
summary(lm.fit2)
```

```{r echo=TRUE}
lm.fit <- lm(medv~lstat)
anova(lm.fit, lm.fit2)
```
```{r echo=TRUE}
par(mfrow=c(2,2))
plot(lm.fit2)
```
```{r echo = TRUE}
lm.fit5 <- lm(medv~poly(lstat, 5))
summary(lm.fit5)
```
```{r echo=TRUE}
summary(lm(medv~log(rm), data = Boston))
```

# Carseats Dataset

### Head Carseats dataset

```{r echo=TRUE}
attach(Carseats)
names(Carseats)
```
```{r echo=TRUE}
lm.fit <- lm(Sales~.+Income:Advertising+Price:Age, data = Carseats)
summary(lm.fit)
```
```{r echo=TRUE}
?contrasts
contrasts(ShelveLoc)
```
```{r echo=TRUE}
LoadLibraries
LoadLibraries()
LoadLibraries <- function() {
  library(MASS)
  library(ISLR)
  print("The libraries have been loaded.")
}
```
```{r}
LoadLibraries
```
```{r}
LoadLibraries()
```





























